import java.util.Base64;

/**
 * Witness recording utility for non-deterministic values.
 * Auto-generated by SVCompRewriter.
 */
public class Witness {

    /**
     * Records a boolean value with witness information and returns it.
     * This allows inline usage: int x = Witness.recordAndReturnValueBoolean(Verifier.nondetInt(), ...);
     * @param value The non-deterministic value
     * @param lineNumber The line number where the value was generated
     * @param cname The class name in bytecode format
     * @param desc The method descriptor in bytecode format
     * @return The same value that was passed in
     */
    public static boolean recordAndReturnValueBoolean(boolean value, int lineNumber, String cname, String desc) {
        String witness = value + "@@@" + lineNumber + "@@@" + cname + "@@@" + desc;
        String enc = Base64.getEncoder().encodeToString(witness.getBytes());
        System.out.println("[WITNESS] " + enc);
        return value;
    }

    /**
     * Records a byte value with witness information and returns it.
     * This allows inline usage: int x = Witness.recordAndReturnValueByte(Verifier.nondetInt(), ...);
     * @param value The non-deterministic value
     * @param lineNumber The line number where the value was generated
     * @param cname The class name in bytecode format
     * @param desc The method descriptor in bytecode format
     * @return The same value that was passed in
     */
    public static byte recordAndReturnValueByte(byte value, int lineNumber, String cname, String desc) {
        String witness = value + "@@@" + lineNumber + "@@@" + cname + "@@@" + desc;
        String enc = Base64.getEncoder().encodeToString(witness.getBytes());
        System.out.println("[WITNESS] " + enc);
        return value;
    }

    /**
     * Records a char value with witness information and returns it.
     * This allows inline usage: int x = Witness.recordAndReturnValueChar(Verifier.nondetInt(), ...);
     * @param value The non-deterministic value
     * @param lineNumber The line number where the value was generated
     * @param cname The class name in bytecode format
     * @param desc The method descriptor in bytecode format
     * @return The same value that was passed in
     */
    public static char recordAndReturnValueChar(char value, int lineNumber, String cname, String desc) {
        String witness = value + "@@@" + lineNumber + "@@@" + cname + "@@@" + desc;
        String enc = Base64.getEncoder().encodeToString(witness.getBytes());
        System.out.println("[WITNESS] " + enc);
        return value;
    }

    /**
     * Records a short value with witness information and returns it.
     * This allows inline usage: int x = Witness.recordAndReturnValueShort(Verifier.nondetInt(), ...);
     * @param value The non-deterministic value
     * @param lineNumber The line number where the value was generated
     * @param cname The class name in bytecode format
     * @param desc The method descriptor in bytecode format
     * @return The same value that was passed in
     */
    public static short recordAndReturnValueShort(short value, int lineNumber, String cname, String desc) {
        String witness = value + "@@@" + lineNumber + "@@@" + cname + "@@@" + desc;
        String enc = Base64.getEncoder().encodeToString(witness.getBytes());
        System.out.println("[WITNESS] " + enc);
        return value;
    }

    /**
     * Records a int value with witness information and returns it.
     * This allows inline usage: int x = Witness.recordAndReturnValueInt(Verifier.nondetInt(), ...);
     * @param value The non-deterministic value
     * @param lineNumber The line number where the value was generated
     * @param cname The class name in bytecode format
     * @param desc The method descriptor in bytecode format
     * @return The same value that was passed in
     */
    public static int recordAndReturnValueInt(int value, int lineNumber, String cname, String desc) {
        String witness = value + "@@@" + lineNumber + "@@@" + cname + "@@@" + desc;
        String enc = Base64.getEncoder().encodeToString(witness.getBytes());
        System.out.println("[WITNESS] " + enc);
        return value;
    }

    /**
     * Records a long value with witness information and returns it.
     * This allows inline usage: int x = Witness.recordAndReturnValueLong(Verifier.nondetInt(), ...);
     * @param value The non-deterministic value
     * @param lineNumber The line number where the value was generated
     * @param cname The class name in bytecode format
     * @param desc The method descriptor in bytecode format
     * @return The same value that was passed in
     */
    public static long recordAndReturnValueLong(long value, int lineNumber, String cname, String desc) {
        String witness = value + "@@@" + lineNumber + "@@@" + cname + "@@@" + desc;
        String enc = Base64.getEncoder().encodeToString(witness.getBytes());
        System.out.println("[WITNESS] " + enc);
        return value;
    }

    /**
     * Records a float value with witness information and returns it.
     * This allows inline usage: int x = Witness.recordAndReturnValueFloat(Verifier.nondetInt(), ...);
     * @param value The non-deterministic value
     * @param lineNumber The line number where the value was generated
     * @param cname The class name in bytecode format
     * @param desc The method descriptor in bytecode format
     * @return The same value that was passed in
     */
    public static float recordAndReturnValueFloat(float value, int lineNumber, String cname, String desc) {
        String witness = value + "@@@" + lineNumber + "@@@" + cname + "@@@" + desc;
        String enc = Base64.getEncoder().encodeToString(witness.getBytes());
        System.out.println("[WITNESS] " + enc);
        return value;
    }

    /**
     * Records a double value with witness information and returns it.
     * This allows inline usage: int x = Witness.recordAndReturnValueDouble(Verifier.nondetInt(), ...);
     * @param value The non-deterministic value
     * @param lineNumber The line number where the value was generated
     * @param cname The class name in bytecode format
     * @param desc The method descriptor in bytecode format
     * @return The same value that was passed in
     */
    public static double recordAndReturnValueDouble(double value, int lineNumber, String cname, String desc) {
        String witness = value + "@@@" + lineNumber + "@@@" + cname + "@@@" + desc;
        String enc = Base64.getEncoder().encodeToString(witness.getBytes());
        System.out.println("[WITNESS] " + enc);
        return value;
    }

    /**
     * Records a String value with witness information and returns it.
     * This allows inline usage: int x = Witness.recordAndReturnValueString(Verifier.nondetInt(), ...);
     * @param value The non-deterministic value
     * @param lineNumber The line number where the value was generated
     * @param cname The class name in bytecode format
     * @param desc The method descriptor in bytecode format
     * @return The same value that was passed in
     */
    public static String recordAndReturnValueString(String value, int lineNumber, String cname, String desc) {
        String witness = value + "@@@" + lineNumber + "@@@" + cname + "@@@" + desc;
        String enc = Base64.getEncoder().encodeToString(witness.getBytes());
        System.out.println("[WITNESS] " + enc);
        return value;
    }

}