"""
Generates the Witness.java helper class with recordValue methods.
"""

from typing import Optional


class WitnessGenerator:
    """Generates Witness.java class for recording non-deterministic values."""

    NONDET_TYPES = [
        ('boolean', 'Boolean'),
        ('byte', 'Byte'),
        ('char', 'Char'),
        ('short', 'Short'),
        ('int', 'Int'),
        ('long', 'Long'),
        ('float', 'Float'),
        ('double', 'Double'),
        ('String', 'String'),
    ]

    @staticmethod
    def generate_witness_class(package: Optional[str] = None) -> str:
        """
        Generate the complete Witness.java class source code.

        Args:
            package: Optional package name for the Witness class

        Returns:
            Complete Java source code for Witness.java
        """
        lines = []

        # Package declaration
        if package:
            lines.append(f"package {package};")
            lines.append("")

        # Imports
        lines.append("import java.util.Base64;")
        lines.append("")

        # Class javadoc
        lines.append("/**")
        lines.append(" * Witness recording utility for non-deterministic values.")
        lines.append(" * Auto-generated by SVCompRewriter.")
        lines.append(" */")
        lines.append("public class Witness {")
        lines.append("")

        # Generate recordAndReturnValue methods for each type (these return the value)
        for java_type, method_suffix in WitnessGenerator.NONDET_TYPES:
            lines.extend(WitnessGenerator._generate_record_and_return_method(java_type, method_suffix))
            lines.append("")

        lines.append("}")

        return '\n'.join(lines)

    @staticmethod
    def _generate_record_and_return_method(java_type: str, method_suffix: str) -> list:
        """Generate a recordAndReturnValue method that logs and returns the value."""
        return [
            f"    /**",
            f"     * Records a {java_type} value with witness information and returns it.",
            f"     * This allows inline usage: int x = Witness.recordAndReturnValue{method_suffix}(Verifier.nondetInt(), ...);",
            f"     * @param value The non-deterministic value",
            f"     * @param lineNumber The line number where the value was generated",
            f"     * @param cname The class name in bytecode format",
            f"     * @param desc The method descriptor in bytecode format",
            f"     * @return The same value that was passed in",
            f"     */",
            f"    public static {java_type} recordAndReturnValue{method_suffix}({java_type} value, int lineNumber, String cname, String desc) {{",
            f"        String witness = value + \"@@@\" + lineNumber + \"@@@\" + cname + \"@@@\" + desc;",
            f"        String enc = Base64.getEncoder().encodeToString(witness.getBytes());",
            f"        System.out.println(\"[WITNESS] \" + enc);",
            f"        return value;",
            f"    }}",
        ]

    @staticmethod
    def write_witness_file(output_path: str, package: Optional[str] = None):
        """
        Write the Witness.java file to disk.

        Args:
            output_path: Path where Witness.java should be written
            package: Optional package name
        """
        content = WitnessGenerator.generate_witness_class(package)

        with open(output_path, 'w') as f:
            f.write(content)

    @staticmethod
    def get_record_method_name(nondet_method: str) -> str:
        """
        Get the corresponding Witness.recordValue* method name for a nonDet* method.

        Args:
            nondet_method: The nonDet method name (e.g., 'nondetInt')

        Returns:
            The recordValue method name (e.g., 'recordValueInt')
        """
        # Map nondetInt -> Int, nondetBoolean -> Boolean, etc.
        # Support both nondetBool and nondetBoolean
        type_mapping = {
            'nondetBoolean': 'Boolean',
            'nondetBool': 'Boolean',  # Alias
            'nondetByte': 'Byte',
            'nondetChar': 'Char',
            'nondetShort': 'Short',
            'nondetInt': 'Int',
            'nondetLong': 'Long',
            'nondetFloat': 'Float',
            'nondetDouble': 'Double',
            'nondetString': 'String',
        }

        return f"recordValue{type_mapping.get(nondet_method, 'Int')}"

    @staticmethod
    def get_java_type(nondet_method: str) -> str:
        """
        Get the Java type for a nonDet* method.

        Args:
            nondet_method: The nonDet method name (e.g., 'nondetInt')

        Returns:
            The Java type (e.g., 'int')
        """
        type_mapping = {
            'nondetBoolean': 'boolean',
            'nondetBool': 'boolean',  # Alias
            'nondetByte': 'byte',
            'nondetChar': 'char',
            'nondetShort': 'short',
            'nondetInt': 'int',
            'nondetLong': 'long',
            'nondetFloat': 'float',
            'nondetDouble': 'double',
            'nondetString': 'String',
        }

        return type_mapping.get(nondet_method, 'int')
